version: '3.9'

services:
  app:
    build:
      context: .  # Use the root directory as the context
      dockerfile: Dockerfile  # Dockerfile is in the root directory
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://admin:LuCPI17mM2GMhJVF@mern.1izuh.mongodb.net/?retryWrites=true&w=majority&appName=MERN


