version: '3.9'

services:
  app:
    build:
      context: .  # Use the root directory as the context
      dockerfile: Dockerfile  # Dockerfile is in the root directory
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/voucherdb
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the root directory into the container's /app directory
  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db  # Persist MongoDB data in the local ./db directory
volumes:
  db-data:
