version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/voucherdb
    depends_on:
      - db
    volumes:
      - ./app:/app
  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
volumes:
  db-data:
